### ISSUE TITLE
Seed data during import

### ISSUE THREAD

**Issue by felideon** [stmichael/data-import#16]
One thing I found myself wanting was the ability to seed data for new
columns during a migration, that did not depend on any source/legacy
columns.  For example:

``` ruby
mapping 'memberid' do |context, id|
   { :account => id, :zone_type => "forward" }
```

In this case zone_type is a new column and for this particular import
block it's always going to be the string "forward" and it has nothing
to do with memberid.  I just used an arbitrary mapping I had and added
this additional seed value.  Maybe something like:

``` ruby
seed =>  { :zone_type => "forward" }
```

Or something to that effect.

**Comment by senny** [comment]
I've opened a pull-request #18 to perform:

``` ruby
import 'Something' do
  seed :column1 => 'value1', :column2 => 'value2'
  seed :column3 => 'value3'
end
```
