### ISSUE TITLE
script block should run in a transaction

### ISSUE THREAD

**Issue by stmichael** [stmichael/data-import#33]

**Comment by senny** [comment]
what happens, when a script block needs it's own transactions? There are databases out there, which don't support nested transactions. This means it would not be possible for a script block to have multiple transactions, which might be necessary. @stmichael what do you think?

**Comment by stmichael** [comment]
That's true, script blocks can have their own transaction handling. But then again, as you said in #32, data consistency would be an issue.

Often you don't have such complex script blocks in which you need your own transaction handling. At least I didn't get to that point. @senny do you see a use case, where that could be useful?

What about we make it configurable whether a script block should run in a transaction like:

``` ruby
script "my script" do
  body :in_transaction => true do
    ...
  end
end
```

**Comment by senny** [comment]
the comment was more a refresher than an actual need for the functionality. I think for the moment we should:
- Wrap the block in a transaction
- Wait for the usecase with multiple transactions to emerge and then add more functionality like `:in_transaction => false`
